### ISSUE TITLE
Faker 1.7 support, or descrease strictness of  faker version dependency

### ISSUE THREAD

**Issue by Insolita** [thephpleague/factory-muffin-faker#12]
subject

**Comment by lubobill1990** [comment]
+1

**Comment by Y0lk** [comment]
Faker is at 1.8. Would be great to see an update on this but it seems like this package hasn't seen any updates in a very long time.

@GrahamCampbell If I make a PR for this, will you merge it and push a new release? 
Thanks.

**Comment by Y0lk** [comment]
Made a PR with the update and all tests pass. Feel free to use my fork until the PR is merged.

**Comment by GrahamCampbell** [comment]
Thanks for the report. This will be fixed in v2.1.0. :)
