### ISSUE TITLE
Keep compatibility with Faker

### ISSUE THREAD

**Issue by Youbility** [thephpleague/factory-muffin-faker#3]
I really like FactoryMuffin 3.0. In my opinion a lot of good design decisions were made for the upcoming version.

What's a show stopper for me at the moment though is very limited compatibility with Faker through the facade. Especially bothering at the current point is one thing. If I'm using Faker directly I can concatenate generated string. So this would work

~~~
$fm->define('Model')->setDefinitions(array(
	'someValue' => $faker->firstName() . ' ' . $faker->randomNumber()
));
~~~

**Using the facade I get an exception, because the returned closure can not be casted to a string.**

~~~
$fm->define('Model')->setDefinitions(array(
	'someValue' => Faker::firstName() . ' ' . Faker::randomNumber()
));
~~~

That's why I'm wondering, why is a closure returned in Faker.php in line 121 (format() method). Why is the result not directly returned like so:

~~~
/**
     * Wrap a faker format in a closure.
     *
     * @param string $formatter The formatter.
     * @param array  $arguments The arguments.
     *
     * @return \Closure
     */
    public function format($formatter, array $arguments = [])
    {
	    return $this->getGenerator()->format( $formatter, $arguments );
    }
~~~

This would already resolve the issue but I guess there would be other drawbacks?

**Comment by scottrobertson** [comment]
If the result was returned directly, all the values would be set at the point of creating the factories, this would result in all of your factories having the same value.

**Comment by GrahamCampbell** [comment]
Yeh, we return a closure. You are not using this correctly. You are going to need to wrap things in a closure yourself if you want this, otherwise all your data would be identical.

**Comment by GrahamCampbell** [comment]
@Youbility This is what you are looking for:

```php
$fm->define('Model')->setDefinitions([
    'someValue' => function () {
        Faker::getGenerator()->firstName() . ' ' . Faker::getGenerator()->randomNumber()
    }
]);
```

The `getGenerator` method will return the instance of `Faker\Generator` that's used under the hood.
