### ISSUE TITLE
I dosent install Faker 1.5

### ISSUE THREAD

**Issue by cherifGsoul** [thephpleague/factory-muffin-faker#4]
when I require the package with composer I figure out that the faker dependency still on 1.4, how I can get 1.5? because I need the Arabic support from faker 1.5 to to generate data!!

**Comment by GrahamCampbell** [comment]
https://github.com/thephpleague/factory-muffin-faker/blob/master/composer.json#L19

**Comment by cherifGsoul** [comment]
I saw that but when installing it I saw 1.4.* I ignore the reason why!

**Comment by cherifGsoul** [comment]
I had to to change my project composer to:
```json
"league/factory-muffin": "~3.0@dev",
"league/factory-muffin-faker": "~1.0@dev"
```

**Comment by GrahamCampbell** [comment]
I've just tagged RC releases on both repos for you btw. It was long overdue tbh. :)

**Comment by cherifGsoul** [comment]
Ok thanks :)
