### ISSUE TITLE
Advantage over using Faker directly?

### ISSUE THREAD

**Issue by ctrlaltdylan** [thephpleague/factory-muffin-faker#5]
Are there any particular advantages over using `factory-muffin-faker` over the faker package it wraps around?

**Comment by GrahamCampbell** [comment]
Yes, it avoids you having to wrap everything in a closure, otherwise it would just be evaluated once, and every model would have identical data.

**Comment by ctrlaltdylan** [comment]
Great thanks for clearing that up.
