### ISSUE TITLE
unique() doesn't scale

### ISSUE THREAD

**Issue by josephzidell** [thephpleague/factory-muffin-faker#6]
`unique()` is pretty easy to understand: a global repository of already-generated data, guaranteed not to be repeated. In our application, we have ~400 factories, and about 1k instances of unique() corresponding to database constraint and about 800 unit tests. We easily surpass the 10k limit and even when upping to 100k. It would be immensely helpful to be able to pass a key: `unique('table.column')->whatever()`. In addition, would be good to have a `clear()` method when we refresh the database.

```
protected function _after()
{
    Faker::unique()->clear();
}
```

If agreed, I can spin up a PR.

**Comment by GrahamCampbell** [comment]
I think it's probably fine to keep this userland, and just allow people to clear this whenever they want to, like, in their tear down method, or whatever. We could perhaps explicitly document this though?

**Comment by josephzidell** [comment]
How to clear?

**Comment by GrahamCampbell** [comment]
Oh, right. Either pass true to the `unique` function, or just call the `reset` method on our facade.

**Comment by josephzidell** [comment]
Will `reset` empty `$this->uniques`?

**Comment by GrahamCampbell** [comment]
D'no, try it out. :)

**Comment by GrahamCampbell** [comment]
I assume so?
