### ISSUE TITLE
IDE support

### ISSUE THREAD

**Issue by krukru** [thephpleague/factory-muffin-faker#9]
I would be nice if we could have some DocBlocks like @property or @method, along the line of https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php#L6-L174

**Comment by sergeivl** [comment]
The problem persists in PHP Strom.

It produces an error in string:
 * @see League\FactoryMuffin\**Faker**\Faker

Undefined namespace Faker

**Comment by wimski** [comment]
This was closed because of #10, but then everything was reverted in #20. So this issue still remains.
